### ISSUE TITLE
Setup fails entirely: vacuum.py AttributeError on VacuumEntityFeature.BATTERY (removed from HA core)

### ISSUE THREAD

**Issue by jimmbuck2k** [astrandb/miele#775]
### The problem

After updating Home Assistant core to 2026.9.0, the entire Miele config entry fails to set up with `setup_error`, taking down all entities (dishwasher included), not just vacuum-related ones.

Root cause: `custom_components/miele/vacuum.py` line 54 references `VacuumEntityFeature.BATTERY` in the `SUPPORTED_FEATURES` bitmask:

```
SUPPORTED_FEATURES = (
    VacuumEntityFeature.TURN_ON
    | VacuumEntityFeature.TURN_OFF
    | VacuumEntityFeature.STATUS
    | VacuumEntityFeature.STATE
    | VacuumEntityFeature.BATTERY   # <-- line 54, no longer exists
    | VacuumEntityFeature.FAN_SPEED
    ...
)
```

`VacuumEntityFeature.BATTERY` was removed from HA core's vacuum entity model (see home-assistant/core#150227, merged 2025-08-07, which removed the battery feature/property from vacuum entities platform-wide in favor of a separate battery sensor). Since this reference is evaluated at module import time, importing `vacuum.py` now raises:

```
AttributeError: type object 'VacuumEntityFeature' has no attribute 'BATTERY'
```

Because `hass.config_entries.async_forward_entry_setups` fails atomically when any platform module fails to import, this one bad reference kills the whole integration for every user, whether or not they actually have a Miele vacuum.

Workaround I applied locally: removed the `| VacuumEntityFeature.BATTERY` line from `vacuum.py`. The `battery_level` property lower in the same file doesn't reference the enum and didn't need changes. Integration reloads cleanly and all entities (including non-vacuum ones) come back immediately.

Suggest removing that one line (and likely dropping/guarding the vacuum platform's battery feature flag generally) in the next release so this doesn't silently break every user's whole integration on core upgrade.

### Version of miele integration having the issue?

2026.2.0

### Version of Home Assistant Core having the issue?

2026.9.0

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py
Integration: miele (custom_components.miele)

Error setting up entry Home Assistant Cloud for miele
Traceback (most recent call last):
  File "/config/custom_components/miele/vacuum.py", line 54, in <module>
    | VacuumEntityFeature.BATTERY
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'VacuumEntityFeature' has no attribute 'BATTERY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 803, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/miele/__init__.py", line 279, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2800, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
```

**Comment by astrandb** [comment]
You have entered this issue in the custom component repo. Note that this repo is deprecated and no new features or fixes will be added. 
The component is a part of HA core since early 2025.
I am sorry, but haven't got the capacity to maintain this deprecated any more. It is not just to remove a single line of code as in your suggested fix. It also requires to keep the development environment up-to-date in order to assure full compatibilty and create the distibution package.
I strongly recommend that you migrate to the core integration. Even if it requires an effort from your side it is the only viable way forward.
